project:
  type: website

website:
  title: "RWorkshop"
  navbar:
    left:
    - text: "R Series"
      menu:
      - text: "Episode 7"
        href: Hands-on_Ex07.html
    - text: "Now You See It"
      href: xxx.html
    - text: "Introduction to QGIS"
      href: xxx.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

